apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netcode-io-demo-server-http
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: netcode-io-demo-server-http
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: high-availability-pool
      securityContext:
        runAsNonRoot: 
      automountServiceAccountToken: false
      containers:
      - name: netcode-io-demo-server-http
        image: redpointgames/netcode-demo-server:latest
        args: [ "--non-interactive", "--server-address", "FROM_PUBLIC", "--http-address", "+" ]
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 33
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 0m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /tmp
            name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netcode-io-demo-server-udp
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: netcode-io-demo-server-udp
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: high-availability-pool
      securityContext:
        runAsNonRoot: true
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - netcode-io-demo-server-http
            topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: false
      hostNetwork: true
      containers:
      - name: netcode-io-demo-server-udp
        image: redpointgames/netcode-demo-server:latest
        args: [ "--non-interactive", "--server-address", "FROM_PUBLIC", "--http-address", "+" ]
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 33
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 0m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 40000
          protocol: UDP
        volumeMounts:
          - mountPath: /tmp
            name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: netcode-http
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: netcode-io-demo-server-http